version: 2
updates:
  - assignees:
      - webczat
    directory: /
    package-ecosystem: nuget
    groups:
      dotnet:
        patterns:
          - "*"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - assignees:
      - webczat
    directory: /
    package-ecosystem: github-actions
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
