<Project>
    <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisMode>All</AnalysisMode>
        <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
        <Deterministic>true</Deterministic>
        <LangVersion>latest</LangVersion>
        <NoWarn>CS1998</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StyleCop.Analyzers" ExcludeAssets="compile" PrivateAssets="all" />
        <AdditionalFiles
            Include="$([MSBuild]::GetPathOfFileAbove('stylecop.json', $(MSBuildProjectDirectory)))" />
        <None
            Include="$([MSBuild]::GetPathOfFileAbove('README.md', $(MSBuildProjectDirectory)))"
            PackagePath="/README.md" Pack="true" />
    </ItemGroup>
</Project>
