<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Webczat.RecordBooster.Sample</RootNamespace>
        <Description>Sample project to test refactorings</Description>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Refactorings/Webczat.RecordBooster.Refactorings.csproj" />
    </ItemGroup>
</Project>
