name: Publish build results
permissions: {}
on:
  workflow_run:
    types: completed
    workflows:
      - Continuous integration

jobs:
  publish-test-results:
    name: Publish test results
    runs-on: ubuntu-latest
    if: contains(fromJSON('["failure", "success", "neutral"]'), github.event.workflow_run.conclusion)
    permissions:
      contents: read
    steps:
      - run: echo '${{toJSON(github.event)}}'
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Download test results
        uses: actions/download-artifact@v7.0.0
        with:
          run-id: ${{github.event.workflow_run.id}}
          name: test-results
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Create token for check writing
        uses: actions/create-github-app-token@v2.2.1
        id: token
        with:
          app-id: ${{vars.GH_APP_CLIENT_ID}}
          private-key: ${{secrets.GH_APP_PRIVATE_KEY}}
          permission-actions: read
          permission-checks: write
      - name: Publish test results as check suite
        uses: dorny/test-reporter@v2.4.0
        with:
          name: Test results
          path: "**/test-results/*.trx"
          reporter: dotnet-trx
          token: ${{steps.token.outputs.token}}
          use-actions-summary: false

  publish-packages:
    name: Publish packages
    runs-on: ubuntu-latest
    if: contains(fromJSON('["success", "neutral"]'), github.event.workflow_run.conclusion)
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup .NET sdk
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: 8.0.x
      - name: Download packages
        uses: actions/download-artifact@v7.0.0
        with:
          run-id: ${{github.event.workflow_run.id}}
          name: packages
          path: packages
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Publish packages
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          for PKG in packages/*.nupkg; do
            dotnet nuget push --skip-duplicate -k "$TOKEN" $PKG
          done
